### ISSUE TITLE
Handling Activity switch

### ISSUE THREAD

**Issue by misrakli** [tehmou/rx-android-architecture#13]
Can you please explain how you would handle switsches between Activities (or Fragments) in this approach? Which component would be responsible to start a new Activity after a Buttonclick in the view?
Thanks & greetings

**Comment by tehmou** [comment]
I would go for an intent based approach that changes the state of the application through the receiver. It should not technically matter which component triggers the switch because each activity and fragment can pull its own data independently after creation.

In case there is some non-trivial logic needed for the new activity to start I would probably call a view model function in the click handler and then take it to the creator of the view model (the parent fragment or activity). However, usually just broadcasting an intent directly from the click handler is enough.

**Comment by misrakli** [comment]
Thank you for your answer.

The decison maybe have an influence on the testability of the components. 
Also i think the view shouldn't know something about the workflow in the app as it's part of the business logic.

Is there a reason why the Activity/Fragment doesn't act as the ViewModel, because it already gets the Actionbar/Menu - Events, the other Events like Button clicks can be taken to the ViewModel (Activity/Fragment) by the view?

**Comment by tehmou** [comment]
@misrakli, the main reasons are reusability and the isolation of logic. I added some explanations about view models on the github pages: http://tehmou.github.io/rx-android-architecture/view-models/, hope it helps.

Orchestrating the events and separating the state into a view model can be challenging, but usually the effort that is required to extract the business logic is worth it at the end. My other example project has more extensive input processing, though it turned out perhaps even a bit too much. You can have a look if you are interested. https://github.com/tehmou/RxMapsAndroid

**Comment by misrakli** [comment]
Thank you for your response...i'll read the article and come back for any other questions ;-)
